version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/tmp/logs
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/llm_service
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - VLLM_API_URL=${VLLM_API_URL}
      - LOGS_DIR=/tmp/logs
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - .:/app
      - ./logs:/tmp/logs
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/llm_service
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - VLLM_API_URL=${VLLM_API_URL}
      - LOGS_DIR=/tmp/logs
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A app.worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LOGS_DIR=/tmp/logs
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=llm_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  bot:
    build: .
    command: python app/run_bot.py
    volumes:
      - .:/app
      - ./logs:/tmp/logs
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/llm_service
      - REDIS_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - VLLM_API_URL=${VLLM_API_URL}
      - LOGS_DIR=/tmp/logs
    depends_on:
      - db
      - redis

volumes:
  postgres_data: 