global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'llm-service'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8001'] 